
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__VehicleControlProxy_hpp__PROXY_MARSHAL_H
#define __dbusxx__VehicleControlProxy_hpp__PROXY_MARSHAL_H

#include <dbus-c++/dbus.h>
#include <cassert>

namespace com {
namespace team2 {

class VehicleControl_proxy
: public ::DBus::InterfaceProxy
{
public:

    VehicleControl_proxy()
    : ::DBus::InterfaceProxy("com.team2.VehicleControl")
    {
        connect_signal(VehicleControl_proxy, SteeringChanged, _SteeringChanged_stub);
        connect_signal(VehicleControl_proxy, ThrottleChanged, _ThrottleChanged_stub);
    }

public:

    /* properties exported by this interface */
public:

    /* methods exported by this interface,
     * this functions will invoke the corresponding methods on the remote objects
     */
    void SetSteering(const double& value)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << value;
        call.member("SetSteering");
        ::DBus::Message ret = invoke_method (call);
    }

    void SetThrottle(const double& value)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << value;
        call.member("SetThrottle");
        ::DBus::Message ret = invoke_method (call);
    }


public:

    /* signal handlers for this interface
     */
    virtual void SteeringChanged(const double& newSteering) = 0;
    virtual void ThrottleChanged(const double& newThrottle) = 0;

private:

    /* unmarshalers (to unpack the DBus message before calling the actual signal handler)
     */
    void _SteeringChanged_stub(const ::DBus::SignalMessage &sig)
    {
        ::DBus::MessageIter ri = sig.reader();

        double newSteering;
        ri >> newSteering;
        SteeringChanged(newSteering);
    }
    void _ThrottleChanged_stub(const ::DBus::SignalMessage &sig)
    {
        ::DBus::MessageIter ri = sig.reader();

        double newThrottle;
        ri >> newThrottle;
        ThrottleChanged(newThrottle);
    }
};

} } 
#endif //__dbusxx__VehicleControlProxy_hpp__PROXY_MARSHAL_H
